language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - go test -v ./util
  - go test -v ./util/route
  - go test -v ./util/MD5
  - go test -v ./util/CoHash
  - go test -v ./util/vector
  - go test -v ./TestPb